{% set name = "biobuddy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4db7a4013bc1b15c8480890d1f657c3e1f35d3374adc6a1d2108674db528954c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
    - wheel
  run:
    - python >={{ python_min }}
    - numpy
    - ezc3d
    - lxml
    - scipy
test:
  imports:
    - biobuddy
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/pyomeca/biobuddy
  summary: 'A generic interface to generate a virtual buddy'
  description: |
    A generic interface to generate a virtual buddy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyomeca/biobuddy

extra:
  recipe-maintainers:
    - EveCharbie
